INSERT INTO products (id, name, description, price) VALUES
(1, 'Trek X-Caliber 8', 'A lightweight aluminum hardtail designed for cross-country riding, offering efficient climbing, responsive handling, and modern trail geometry.', 1499.00),
(2, 'Specialized Stumpjumper Comp', 'A versatile full-suspension trail bike built to handle everything from flow trails to technical descents with confidence and balance.', 4199.00),
(3, 'Santa Cruz Hightower V3', 'A premium all-mountain bike blending efficient pedaling with aggressive descending performance for demanding trail riders.', 5899.00),
(4, 'Giant Trance X E+ Pro 29', 'An electric mountain bike featuring a powerful mid-drive motor and long-range battery for extended trail adventures.', 6799.00),
(5, 'Commencal Clash Ride', 'A rugged enduro-focused bike designed for steep terrain, bike park laps, and aggressive downhill riding.', 3299.00),
(6, 'Yeti SB140', 'A high-performance trail bike designed for aggressive all-mountain riding, blending playful handling with serious descending capability.', 6299.00),
(7, 'Cannondale Trail SE 2', 'A capable hardtail mountain bike aimed at beginner to intermediate riders looking for durability, comfort, and confidence on local trails.', 1899.00);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Ethan M.', 5, 'The Trek X-Caliber 8 has been an excellent introduction to serious mountain biking for me. It climbs efficiently on longer XC trails and feels light and responsive when accelerating out of corners. I have ridden it on smoother green and blue trails as well as some mild technical sections, and it handles everything predictably. The geometry feels modern without being intimidating, and it has helped me build confidence quickly.', NOW(), 1),
('Laura P.', 4, 'As a newer rider, I really appreciate how forgiving and comfortable this hardtail feels. The X-Caliber 8 is efficient on climbs and easy to control on descents. While it can feel a bit harsh on rocky sections compared to a full-suspension bike, it makes up for it with simplicity and reliability. It is a great bike for fitness rides and weekend trail adventures.', NOW(), 1),
('Ryan T.', 5, 'I bought the X-Caliber 8 for cross-country riding and light trail use, and it has exceeded my expectations. The bike accelerates quickly, tracks well on climbs, and feels nimble through tight turns. It is also low maintenance, which is perfect for someone who wants to ride more and wrench less. Fantastic value for the price.', NOW(), 1),
('Chris W.', 4, 'This bike shines on smoother trails and rolling terrain. It feels fast and efficient, especially on longer rides where weight matters. I would recommend it to anyone who enjoys endurance rides or is getting into trail riding without jumping straight into full suspension.', NOW(), 1),
('Megan S.', 5, 'The X-Caliber 8 has been a great all-around bike for me. It is comfortable, predictable, and easy to upgrade over time. I have used it on local valley trails and longer scenic rides, and it performs consistently every time.', NOW(), 1),

('Daniel K.', 5, 'The Specialized Stumpjumper Comp is an incredibly versatile trail bike. It pedals efficiently uphill and absolutely comes alive on descents. I ride a mix of flow trails and technical sections, and this bike feels perfectly at home in both environments. Suspension feels balanced and supportive, even on longer, rough descents.', NOW(), 2),
('Ashley R.', 4, 'What I love most about the Stumpjumper is how confidence-inspiring it feels. The geometry makes steep descents feel manageable, and the bike remains stable without feeling sluggish. It is a bit pricey, but the performance justifies the cost.', NOW(), 2),
('Mark L.', 5, 'This bike does everything well. From smooth blue trails to rocky black runs, the Stumpjumper Comp handles it all. The suspension is plush without being overly soft, and it still climbs better than I expected for a full-suspension trail bike.', NOW(), 2),
('Tom B.', 4, 'I use this bike for long trail days, and it remains comfortable for hours in the saddle. It is not a pure downhill machine, but that is not what it is meant for. For all-around trail riding, it is one of the best bikes I have owned.', NOW(), 2),
('Samantha J.', 5, 'The Stumpjumper Comp has completely changed how I approach trails. I feel faster, more confident, and less fatigued after long rides. It is a fantastic do-it-all trail bike.', NOW(), 2),

('Kevin D.', 5, 'The Santa Cruz Hightower is an absolute monster on technical trails. It climbs efficiently for its size and feels incredibly stable when descending steep, rocky terrain. The build quality is outstanding, and the bike feels solid and confidence-inspiring at high speeds.', NOW(), 3),
('Paul N.', 5, 'This bike is perfect for aggressive trail riding. The suspension handles big hits smoothly, and the geometry encourages you to push harder. It feels equally comfortable on long climbs and fast, rough descents.', NOW(), 3),
('Alex H.', 4, 'The Hightower is a premium bike with premium performance. It is not the lightest option, but the stability and control it offers on challenging trails more than make up for it. Ideal for riders who want one bike to handle almost everything.', NOW(), 3),
('Jordan F.', 5, 'I ride a lot of black and double-black trails, and the Hightower gives me confidence in situations where my old bike felt overwhelmed. It tracks well through rock gardens and feels planted on steep descents.', NOW(), 3),
('Ben C.', 5, 'This bike strikes an excellent balance between efficiency and aggression. It feels fast, stable, and incredibly capable. Worth every dollar if you ride challenging terrain regularly.', NOW(), 3),

('Natalie V.', 5, 'The Giant Trance X E+ Pro has completely changed how far I can ride in a single day. The motor assistance feels natural and smooth, and I can still get a good workout while covering much more ground. It is perfect for scenic rides and long climbs.', NOW(), 4),
('Eric M.', 4, 'This e-bike is powerful without feeling overwhelming. The battery range is excellent, and the bike handles well on both climbs and descents. It is heavier than a traditional bike, but the motor more than compensates.', NOW(), 4),
('Sophia L.', 5, 'I love how accessible this bike makes tougher trails. Long climbs that used to feel exhausting are now enjoyable. The build quality is solid, and the suspension keeps everything comfortable even on rough terrain.', NOW(), 4),
('James R.', 4, 'The Trance X E+ Pro is great for extended trail rides and exploring new areas. It feels stable and predictable, and the motor engagement is smooth. A great option for riders looking to extend their range.', NOW(), 4),
('Olivia K.', 5, 'This e-MTB has made riding more fun and less intimidating. I can ride with more experienced friends and keep up without feeling drained. Highly recommended for long-distance trail adventures.', NOW(), 4),

('Dylan S.', 5, 'The Commencal Clash Ride is built for aggressive riding. It feels incredibly stable on steep descents and handles jumps and drops with ease. This bike thrives in bike parks and rough terrain.', NOW(), 5),
('Aaron T.', 4, 'This bike is not subtle, but it is incredibly capable. It is heavier and less efficient on climbs, but once pointed downhill it absolutely shines. Perfect for riders who prioritize descending.', NOW(), 5),
('Lucas P.', 5, 'I bought the Clash Ride for enduro racing and bike park days, and it delivers exactly what I wanted. It is tough, confidence-inspiring, and feels unshakeable at speed.', NOW(), 5),
('Nathan G.', 4, 'The Clash Ride feels planted and predictable on technical descents. It is not a trail bike meant for long climbs, but for aggressive riding it is excellent. Very durable and well-built.', NOW(), 5),
('Victor E.', 5, 'This bike encourages you to push your limits. It handles steep lines and rough sections effortlessly and feels like it can take endless abuse. Ideal for experienced riders who love downhill-focused terrain.', NOW(), 5),

('Brandon H.', 5, 'The Yeti SB140 is hands-down the most fun trail bike I have ever ridden. It feels incredibly playful on flow trails while still being composed and stable on steep, technical descents. The suspension design provides excellent traction when climbing, and the bike rewards aggressive riding without feeling overwhelming. It is expensive, but the performance and ride quality are on another level.', NOW(), 6),
('Liam T.', 5, 'This bike strikes an amazing balance between agility and stability. I ride a mix of blue and black trails, and the SB140 feels perfectly tuned for that kind of riding. It corners sharply, pops off small features, and stays planted through rock gardens. Definitely a premium bike for riders who like to push the pace.', NOW(), 6),
('Sophia M.', 4, 'The SB140 feels very refined and capable, especially on descents. The suspension does an excellent job smoothing out rough sections, and the geometry inspires confidence. My only hesitation is the price point, which makes it less accessible, but from a performance standpoint it is excellent.', NOW(), 6),
('Kevin R.', 3, 'While the SB140 rides incredibly well, I struggled to justify the cost. For casual trail riding, it feels like more bike than necessary, and I did not notice a huge improvement over more affordable trail bikes. Amazing performance, but not the best value unless you really ride hard.', NOW(), 6),
('Daniel W.', 2, 'The bike performs well downhill, but I found it uncomfortable on long, mellow rides. The aggressive geometry felt tiring on flatter trails, and maintenance costs have been higher than expected. It seems better suited for very specific riding styles.', NOW(), 6),

('Emily S.', 4, 'The Cannondale Trail SE 2 has been a solid and dependable bike for my local trails. It feels stable, climbs well, and is forgiving enough for a newer rider. I use it mainly on green and blue trails, and it performs reliably without needing constant adjustments.', NOW(), 7),
('Josh P.', 5, 'As someone getting back into mountain biking, this bike has been perfect. It is comfortable, easy to control, and feels durable. I appreciate the simplicity of a hardtail and how efficient it feels on longer rides. Great bike for building skills.', NOW(), 7),
('Rachel L.', 4, 'The Trail SE 2 is a great all-around hardtail. It handles roots and small rocks well and feels predictable on descents. It is not flashy, but it gets the job done and feels like it will last for years.', NOW(), 7),
('Aaron D.', 3, 'This bike works fine on smoother trails, but it struggles on more technical terrain. The lack of rear suspension makes rough sections uncomfortable, and I found myself wishing for more compliance. It is good for beginners but has clear limitations.', NOW(), 7),
('Michael B.', 2, 'I was disappointed with how harsh the ride feels on rocky trails. While the bike is sturdy, it does not inspire confidence on steeper or rougher descents. For the price, I expected better trail capability, and I would recommend upgrading to full suspension if possible.', NOW(), 7);
